# An alternative dev configuration the the more simple devserver (easier to debug but you lose dev-prod parity)
# Note: migrations are not run automatically!
version: "{{ cookiecutter.docker_compose_version }}"

x-develop:
  &develop
    volumes:
    - "${PWD}:/app"
    privileged: true
    tty: true

services:
  web:
    <<: *develop
    command: ["django-admin", "runserver", "0.0.0.0:8000"]
    environment:
      DJANGO_ALLOWED_HOSTS: "*"
    stop_signal: SIGINT
    ports:
    - "8000:80"

  celery:
    <<: *develop
    command: ["celery", "-A", "{{ cookiecutter.django_project_name }}", "worker", "-l", "debug"]
